# Start with a lightweight PyTorch base image
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel
# Set the working directory inside the container
WORKDIR /app

COPY vllm_requirements.txt .
RUN pip install --no-cache-dir -r vllm_requirements.txt

ENV PYTHONPATH="/app"

